export const contacts = [
    {
        first_name: "Sarah",
        last_name: "Johnson",
        zip_code: "90210",
        date_of_birth: "1985-03-15",
    },
    {
        first_name: "Michael",
        last_name: "Smith",
        zip_code: "60601",
        date_of_birth: "1992-08-22",
    },
    {
        first_name: "Emma",
        last_name: "Williams",
        zip_code: "10001",
        date_of_birth: "1988-12-05",
    },
    {
        first_name: "James",
        last_name: "Brown",
        zip_code: "75001",
        date_of_birth: "1975-06-30",
    },
    {
        first_name: "Maria",
        last_name: "Garcia",
        zip_code: "02108",
        date_of_birth: "1995-01-17",
    },
    {
        first_name: "David",
        last_name: "Miller",
        zip_code: "98101",
        date_of_birth: "1982-11-09",
    },
    {
        first_name: "Jennifer",
        last_name: "Davis",
        zip_code: "33101",
        date_of_birth: "1990-04-25",
    },
    {
        first_name: "Robert",
        last_name: "Anderson",
        zip_code: "19103",
        date_of_birth: "1978-09-12",
    },
    {
        first_name: "Lisa",
        last_name: "Martinez",
        zip_code: "80202",
        date_of_birth: "1987-07-03",
    },
    {
        first_name: "John",
        last_name: "Taylor",
        zip_code: "20001",
        date_of_birth: "1993-05-28",
    },
    {
        first_name: "Ashley",
        last_name: "White",
        zip_code: "30301",
        date_of_birth: "1991-10-16",
    },
    {
        first_name: "Joshua",
        last_name: "Martin",
        zip_code: "94016",
        date_of_birth: "1980-04-11",
    },
    {
        first_name: "Olivia",
        last_name: "Thomas",
        zip_code: "75201",
        date_of_birth: "1996-09-07",
    },
    {
        first_name: "Matthew",
        last_name: "Jackson",
        zip_code: "98109",
        date_of_birth: "1983-02-14",
    },
    {
        first_name: "Sophia",
        last_name: "Lopez",
        zip_code: "60605",
        date_of_birth: "1989-07-20",
    },
    {
        first_name: "Christopher",
        last_name: "Harris",
        zip_code: "02110",
        date_of_birth: "1977-05-19",
    },
    {
        first_name: "Isabella",
        last_name: "Gonzalez",
        zip_code: "33109",
        date_of_birth: "1997-12-03",
    },
    {
        first_name: "Andrew",
        last_name: "Clark",
        zip_code: "10011",
        date_of_birth: "1981-06-02",
    },
    {
        first_name: "Elizabeth",
        last_name: "Lewis",
        zip_code: "94105",
        date_of_birth: "1994-03-21",
    },
    {
        first_name: "Anthony",
        last_name: "Walker",
        zip_code: "77001",
        date_of_birth: "1986-11-29",
    },
    {
        first_name: "Charlotte",
        last_name: "Young",
        zip_code: "20002",
        date_of_birth: "1988-08-12",
    },
    {
        first_name: "Daniel",
        last_name: "Hall",
        zip_code: "30303",
        date_of_birth: "1992-01-01",
    },
    {
        first_name: "Grace",
        last_name: "Allen",
        zip_code: "75202",
        date_of_birth: "1993-09-23",
    },
    {
        first_name: "Ethan",
        last_name: "Hernandez",
        zip_code: "80203",
        date_of_birth: "1984-12-15",
    },
    {
        first_name: "Abigail",
        last_name: "King",
        zip_code: "19104",
        date_of_birth: "1995-04-08",
    },
    {
        first_name: "Liam",
        last_name: "Scott",
        zip_code: "98103",
        date_of_birth: "1987-02-26",
    },
    {
        first_name: "Amelia",
        last_name: "Green",
        zip_code: "94018",
        date_of_birth: "1998-11-17",
    },
    {
        first_name: "Henry",
        last_name: "Baker",
        zip_code: "60603",
        date_of_birth: "1979-06-22",
    },
    {
        first_name: "Emily",
        last_name: "Adams",
        zip_code: "02112",
        date_of_birth: "1986-08-29",
    },
    {
        first_name: "Mason",
        last_name: "Nelson",
        zip_code: "33102",
        date_of_birth: "1982-03-03",
    },
];
